# Generated by Django 3.0.3 on 2020-02-15 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_article_publishedat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='auther',
            new_name='author',
        ),
    ]
